# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2532df562e8e14cab5fc6c17b38a353a775db9f5d72f0392ac8404d71e4d41e369c85ee5a19e654f46495500f3270c26bd54231276e8243abc41a85aafdbb603

test:
  secret_key_base: 1b03d22e3599ded692f5c2723c37a2b9556e128f599c6ed6dea73ec0b491d765286c5aeb53604be4a0b206af135cd5bd94e10be4a25bea2f22a7e3ea1c4cbac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
